### ISSUE TITLE
Minecraft tries to download legacy.json on start, fails. 

### ISSUE THREAD

**Issue by lsck0** [North-West-Wind/CurseForge-CLI#7]
When starting modpacks in the launcher downloaded via this cli tool this error occurs:
```
Failed to download file.
Name: legacy.json
URL: http://s3.amazonaws.com/Minecraft.Download/indexes/legacy.json
Error details: Failed to connect to s3.amazonaws.com port 80 after 60 ms: Connection Refused
Filename on disk: legacy.json
Path: /home/luca/.minecraft/assets/indexes/legacy.json
Exists: Nonexistent
```
Vanilla and self-modded versions start without any problems.

**Comment by North-West-Wind** [comment]
Any modpack?

**Comment by lsck0** [comment]
Yes. I've tried 10 different random modpacks, all throw the same error.

**Comment by North-West-Wind** [comment]
Can you send me the ID of those modpacks? And maybe a log file from one of them too.

**Comment by lsck0** [comment]
For example 227724 (FTB Infinity Evolved for 1.7.10):
```
Iterated through 132 projects. 132 success, 0 failed, 0 skipped
Created profile for FTB Infinity Evolved.
Finished download of FTB Infinity Evolved
```
![mc-log](https://user-images.githubusercontent.com/49280340/163709228-52de4745-c42c-4f81-9a66-8ab755725185.png)

Other modpacks i tried, all exited with the exact same log as above: 285109 296062 381671

**Comment by North-West-Wind** [comment]
Did you make any profile edit (in Minecraft launcher) before starting your game?

Alright, I think the problem might be the profile generated by the program. It's probably due to `lastVersionId` being a version that does not exist. Please note that the program will not install any client, and the `lastVersionId` might not be matching the name of installed version.

A temporary fix will be editing `lastVersionId` to an existing version. In the case of FTB Infinity Evolverd, change that to `1.7.10-Forge10.13.4.1614-1.7.10`

**Comment by lsck0** [comment]
I did not edit the generated profile. Thank you for your work :+1:

**Comment by North-West-Wind** [comment]
I figured the best I can do is a warning. Added in v1.3.0.
